/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmagent_free: (a: number, b: number) => void;
export const __wbg_wasmgame_free: (a: number, b: number) => void;
export const __wbg_wasmonlinedqn_free: (a: number, b: number) => void;
export const wasmagent_export_weights: (a: number) => [number, number];
export const wasmagent_get_stats: (a: number) => any;
export const wasmagent_load_dqn_weights: (a: number, b: number, c: number) => number;
export const wasmagent_load_weights: (a: number, b: number, c: number) => number;
export const wasmagent_new: (a: number, b: number) => number;
export const wasmagent_reset: (a: number) => void;
export const wasmagent_set_learning: (a: number, b: number) => void;
export const wasmagent_step: (a: number) => any;
export const wasmagent_train_steps: (a: number, b: number) => any;
export const wasmgame_evaluate_actions: (a: number, b: number, c: number, d: number) => [number, number];
export const wasmgame_get_state: (a: number) => [number, number];
export const wasmgame_new: () => number;
export const wasmgame_reset: (a: number) => void;
export const wasmgame_reset_at_level: (a: number, b: number) => void;
export const wasmgame_tick: (a: number, b: number, c: number) => any;
export const wasmgame_tick_input: (a: number, b: number, c: number, d: number, e: number) => any;
export const wasmonlinedqn_export_weights: (a: number) => [number, number];
export const wasmonlinedqn_get_q_values: (a: number, b: number, c: number) => [number, number];
export const wasmonlinedqn_get_stats: (a: number) => any;
export const wasmonlinedqn_load_weights: (a: number, b: number, c: number) => number;
export const wasmonlinedqn_new: () => number;
export const wasmonlinedqn_pick_action: (a: number, b: number, c: number) => number;
export const wasmonlinedqn_set_epsilon: (a: number, b: number) => void;
export const wasmonlinedqn_set_lr: (a: number, b: number) => void;
export const wasmonlinedqn_step: (a: number) => any;
export const wasmonlinedqn_train_steps: (a: number, b: number) => any;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_start: () => void;
